services:
  db:
    image: postgres:16.3
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - "5432:5432" 

volumes:
  db_data:
